### PR TITLE
Update harbour-chatgpt-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Update Swedish translation

### CODE REVIEW

**Comment by RikudouSage** [comment]
@eson57 I've added a Transifex project if you wish to move your translation efforts there: https://explore.transifex.com/rikudou-sage/chatgpt/

**Comment by eson57** [comment]
Yes, I would if I could. Seem to not work as intended, when I hit the "Join" button. I just get redirected to my last logged in project (SailfishOS:Chum GUI).

**Comment by eson57** [comment]
I think you can just give me (eson) access to the project.

**Comment by RikudouSage** [comment]
@eson57 I just accepted your join request, all should work now.

**Pull request merged**
